// Map list mirrors src/core/game/Game.ts GameMapType + mapCategories.
// Keep in sync with the OpenFront repo when new maps are added.

export const MAP_CATEGORIES = [
  {
    name: "Continental",
    maps: [
      "World",
      "Giant World Map",
      "North America",
      "South America",
      "Europe",
      "Europe Classic",
      "Asia",
      "Africa",
      "Oceania",
      "Antarctica",
    ],
  },
  {
    name: "Regional",
    maps: [
      "Britannia Classic",
      "Britannia",
      "Black Sea",
      "Gateway to the Atlantic",
      "Between Two Seas",
      "Iceland",
      "East Asia",
      "Mena",
      "Australia",
      "Faroe Islands",
      "Falkland Islands",
      "Baikal",
      "Halkidiki",
      "Strait of Gibraltar",
      "Italia",
      "Japan",
      "Montreal",
      "Gulf of St. Lawrence",
      "Lisbon",
      "New York City",
      "Manicouagan",
      "Lemnos",
      "Two Lakes",
      "Strait of Hormuz",
      "Amazon River",
      "Bosphorus Straits",
      "Bering Strait",
      "Yenisei",
      "Hawaii",
      "Alps",
      "Nile Delta",
      "Arctic",
      "San Francisco",
      "Aegean",
      "Mare Nostrum",
      "Great Lakes",
      "Strait Of Malacca",
      "Conakry",
      "Caucasus",
      "Los Angeles",
      "Bering Sea",
      "ArchipelagoSea",
      "Baja California",
      "Middle East",
      "Taiwan Strait",
      "The Straits",
    ],
  },
  {
    name: "Fantasy",
    maps: [
      "Pangaea",
      "Pluto",
      "Mars",
      "Deglaciated Antarctica",
      "Achiran",
      "Baikal Nuke Wars",
      "Four Islands",
      "Svalmel",
      "Surrounded",
      "Traders Dream",
      "Passage",
      "MilkyWay",
      "Dyslexdria",
      "Luna",
    ],
  },
  {
    name: "Arcade",
    maps: ["The Box", "Didier", "Didier France", "Sierpinski"],
  },
  {
    name: "Tournament",
    maps: [
      "Tourney 2 Teams",
      "Tourney 3 Teams",
      "Tourney 4 Teams",
      "Tourney 8 Teams",
    ],
  },
];

export const MODIFIERS = [
  { key: "isRandomSpawn", label: "Random spawn" },
  { key: "isCompact", label: "Compact map" },
  { key: "isCrowded", label: "Crowded" },
  { key: "isHardNations", label: "Hard nations" },
  { key: "isAlliancesDisabled", label: "Alliances disabled" },
  { key: "isPortsDisabled", label: "Ports disabled" },
  { key: "isNukesDisabled", label: "Nukes disabled" },
  { key: "isSAMsDisabled", label: "SAMs disabled" },
  { key: "isPeaceTime", label: "Peace time" },
  { key: "isWaterNukes", label: "Water nukes" },
];

export const TEAM_PRESETS = [
  { value: "any", label: "Any" },
  { value: "2", label: "2 teams" },
  { value: "3", label: "3 teams" },
  { value: "4", label: "4 teams" },
  { value: "5", label: "5 teams" },
  { value: "6", label: "6 teams" },
  { value: "7", label: "7 teams" },
  { value: "8", label: "8 teams" },
  { value: "Duos", label: "Duos (2/team)" },
  { value: "Trios", label: "Trios (3/team)" },
  { value: "Quads", label: "Quads (4/team)" },
  { value: "Humans Vs Nations", label: "Humans Vs Nations" },
];
